#############################################################################
#
# Tr8n Default Gender Rules
#
#############################################################################

en-US:
  rule1:
    operator:   is 
    value:      male
  rule2:
    operator:   is 
    value:      female
  rule3:
    operator:   is 
    value:      unknown
